name: CI

on: [push, workflow_dispatch]

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Download

      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract

      run: Expand-Archive ngrok.zip

    - name: Auth

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS

      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "X" -Password (ConvertTo-SecureString -AsPlainText "12345678Xx" -Force)

    - name: Create Tunnel

      run: .\ngrok\ngrok.exe tcp 3389

    - name: Install Visual Studio Code

      run: Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?LinkID=852157 -OutFile VSCodeSetup.exe; Start-Process .\VSCodeSetup.exe -ArgumentList '/VERYSILENT /NORESTART' -Wait

    - name: Clone Repository

      run: git clone https://github.com/ai-to-ai/Auto-Gmail-Creator $env:USERPROFILE\Desktop\Auto-Gmail-Creator
